components:
  schemas:
    APIError:
      $defs:
        APIError:
          additionalProperties: false
          properties:
            Code:
              type: integer
            Domain:
              type: string
            Message:
              type: string
            Reason:
              type: string
          type: object
      $id: https://github.com/forkbombeu/credimi/pkg/internal/apierror/api-error
      $ref: '#/$defs/APIError'
      $schema: https://json-schema.org/draft/2020-12/schema
    CancelMyCheckRunRequestResponse:
      $defs:
        CancelMyCheckRunRequestResponse:
          additionalProperties: false
          properties:
            message:
              type: string
            namespace:
              type: string
            run_id:
              type: string
            status:
              type: string
            time:
              type: string
            workflow_id:
              type: string
          type: object
      $id: https://github.com/forkbombeu/credimi/pkg/internal/apis/handlers/cancel-my-check-run-request-response
      $ref: '#/$defs/CancelMyCheckRunRequestResponse'
      $schema: https://json-schema.org/draft/2020-12/schema
    ChecksLogsRequestResponse:
      $defs:
        ChecksLogsRequestResponse:
          additionalProperties: false
          properties:
            channel:
              type: string
            message:
              type: string
            namespace:
              type: string
            run_id:
              type: string
            status:
              type: string
            time:
              type: string
            workflow_id:
              type: string
          type: object
      $id: https://github.com/forkbombeu/credimi/pkg/internal/apis/handlers/checks-logs-request-response
      $ref: '#/$defs/ChecksLogsRequestResponse'
      $schema: https://json-schema.org/draft/2020-12/schema
    ExportMyCheckRun:
      $defs:
        Export:
          additionalProperties: false
          properties:
            checkId:
              type: string
            config:
              type: object
            input:
              type: object
            runId:
              type: string
          type: object
        ExportMyCheckRun:
          additionalProperties: false
          properties:
            export:
              $ref: '#/$defs/Export'
          type: object
      $id: https://github.com/forkbombeu/credimi/pkg/internal/apis/handlers/export-my-check-run
      $ref: '#/$defs/ExportMyCheckRun'
      $schema: https://json-schema.org/draft/2020-12/schema
    GetMyCheckRunHistory:
      $defs:
        Event:
          additionalProperties: false
          properties:
            attributes:
              type: string
            details:
              type: string
            eventId:
              type: string
            eventTime:
              type: string
            eventType:
              type: string
          type: object
        GetMyCheckRunHistory:
          additionalProperties: false
          properties:
            checkId:
              type: string
            count:
              type: integer
            history:
              items:
                $ref: '#/$defs/Event'
              type: array
            namespace:
              type: string
            runId:
              type: string
            time:
              type: string
          type: object
      $id: https://github.com/forkbombeu/credimi/pkg/internal/apis/handlers/get-my-check-run-history
      $ref: '#/$defs/GetMyCheckRunHistory'
      $schema: https://json-schema.org/draft/2020-12/schema
    GetMyCheckRunRequestResponse:
      $defs:
        GetMyCheckRunRequestResponse:
          additionalProperties: false
          properties:
            workflow_execution:
              $ref: '#/$defs/WorkflowExecution'
          type: object
        MessageState:
          additionalProperties: false
          properties:
            details:
              type: string
            state:
              type: string
          type: object
        WorkflowExecution:
          additionalProperties: false
          properties:
            assignedBuildId:
              type: string
            canBeTerminated:
              type: boolean
            endTime:
              type: string
            executionTime:
              type: string
            historyEvents:
              type: string
            historySizeBytes:
              type: string
            id:
              type: string
            isRunning:
              type: boolean
            name:
              type: string
            parentNamespaceId:
              type: string
            runId:
              type: string
            startTime:
              type: string
            status:
              $ref: '#/$defs/MessageState'
            taskQueue:
              type: string
            url:
              type: string
          type: object
      $id: https://github.com/forkbombeu/credimi/pkg/internal/apis/handlers/get-my-check-run-request-response
      $ref: '#/$defs/GetMyCheckRunRequestResponse'
      $schema: https://json-schema.org/draft/2020-12/schema
    ListMyCheckRunsRequestResponse:
      $defs:
        ListMyCheckRunsRequestResponse:
          additionalProperties: false
          properties:
            executions:
              items:
                $ref: '#/$defs/WorkflowExecution'
              type: array
          type: object
        MessageState:
          additionalProperties: false
          properties:
            details:
              type: string
            state:
              type: string
          type: object
        WorkflowExecution:
          additionalProperties: false
          properties:
            assignedBuildId:
              type: string
            canBeTerminated:
              type: boolean
            endTime:
              type: string
            executionTime:
              type: string
            historyEvents:
              type: string
            historySizeBytes:
              type: string
            id:
              type: string
            isRunning:
              type: boolean
            name:
              type: string
            parentNamespaceId:
              type: string
            runId:
              type: string
            startTime:
              type: string
            status:
              $ref: '#/$defs/MessageState'
            taskQueue:
              type: string
            url:
              type: string
          type: object
      $id: https://github.com/forkbombeu/credimi/pkg/internal/apis/handlers/list-my-check-runs-request-response
      $ref: '#/$defs/ListMyCheckRunsRequestResponse'
      $schema: https://json-schema.org/draft/2020-12/schema
    ListMyChecksRequestResponse:
      $defs:
        ListMyChecksRequestResponse:
          additionalProperties: false
          properties:
            executions:
              items:
                $ref: '#/$defs/WorkflowExecution'
              type: array
          type: object
        MessageState:
          additionalProperties: false
          properties:
            details:
              type: string
            state:
              type: string
          type: object
        WorkflowExecution:
          additionalProperties: false
          properties:
            assignedBuildId:
              type: string
            canBeTerminated:
              type: boolean
            endTime:
              type: string
            executionTime:
              type: string
            historyEvents:
              type: string
            historySizeBytes:
              type: string
            id:
              type: string
            isRunning:
              type: boolean
            name:
              type: string
            parentNamespaceId:
              type: string
            runId:
              type: string
            startTime:
              type: string
            status:
              $ref: '#/$defs/MessageState'
            taskQueue:
              type: string
            url:
              type: string
          type: object
      $id: https://github.com/forkbombeu/credimi/pkg/internal/apis/handlers/list-my-checks-request-response
      $ref: '#/$defs/ListMyChecksRequestResponse'
      $schema: https://json-schema.org/draft/2020-12/schema
    ReRunCheckRequest:
      $defs:
        ReRunCheckRequest:
          additionalProperties: false
          properties:
            config:
              type: object
          type: object
      $id: https://github.com/forkbombeu/credimi/pkg/internal/apis/handlers/re-run-check-request
      $ref: '#/$defs/ReRunCheckRequest'
      $schema: https://json-schema.org/draft/2020-12/schema
    ReRunCheckRequestResponse:
      $defs:
        ReRunCheckRequestResponse:
          additionalProperties: false
          properties:
            run_id:
              type: string
            workflow_id:
              type: string
          type: object
      $id: https://github.com/forkbombeu/credimi/pkg/internal/apis/handlers/re-run-check-request-response
      $ref: '#/$defs/ReRunCheckRequestResponse'
      $schema: https://json-schema.org/draft/2020-12/schema
    TerminateMyCheckRunRequestResponse:
      $defs:
        TerminateMyCheckRunRequestResponse:
          additionalProperties: false
          properties:
            message:
              type: string
            namespace:
              type: string
            run_id:
              type: string
            status:
              type: string
            time:
              type: string
            workflow_id:
              type: string
          type: object
      $id: https://github.com/forkbombeu/credimi/pkg/internal/apis/handlers/terminate-my-check-run-request-response
      $ref: '#/$defs/TerminateMyCheckRunRequestResponse'
      $schema: https://json-schema.org/draft/2020-12/schema
info:
  contact:
    email: support@forkbomb.eu
    name: credimi Support
    url: https://forkbomb.solutions
  description: credimi API Gateway for managing EUDI-ARF compliance checks...
  title: "credimi \U0001F440 API Gateway"
  version: 1.4.0
openapi: 3.0.1
paths:
  /api/my/checks:
    get:
      description: List all checks for the authenticated user
      operationId: listMyChecks
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListMyChecksRequestResponse'
          description: Successful response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: An unexpected error occurred.
      summary: Get a list of all checks for the authenticated user
  /api/my/checks/{checkId}/runs:
    get:
      description: List all runs for a specific check
      operationId: listMyCheckRuns
      parameters:
        - description: The ID for the checkId.
          in: path
          name: checkId
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListMyCheckRunsRequestResponse'
          description: Successful response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: An unexpected error occurred.
      summary: Get a list of all runs for a specific check
  /api/my/checks/{checkId}/runs/{runId}:
    get:
      description: Get details of a specific run for a check
      operationId: getMyCheckRun
      parameters:
        - description: The ID for the checkId.
          in: path
          name: checkId
          required: true
          schema:
            type: string
        - description: The ID for the runId.
          in: path
          name: runId
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMyCheckRunRequestResponse'
          description: Successful response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: An unexpected error occurred.
      summary: Get details of a specific run for a check
  /api/my/checks/{checkId}/runs/{runId}/cancel:
    post:
      description: Cancel a specific check run
      operationId: cancelMyCheckRun
      parameters:
        - description: The ID for the checkId.
          in: path
          name: checkId
          required: true
          schema:
            type: string
        - description: The ID for the runId.
          in: path
          name: runId
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CancelMyCheckRunRequestResponse'
          description: Successful response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: An unexpected error occurred.
      summary: Cancel a specific check run
  /api/my/checks/{checkId}/runs/{runId}/export:
    get:
      description: Export a specific check run
      operationId: exportMyCheckRun
      parameters:
        - description: The ID for the checkId.
          in: path
          name: checkId
          required: true
          schema:
            type: string
        - description: The ID for the runId.
          in: path
          name: runId
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportMyCheckRun'
          description: Successful response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: An unexpected error occurred.
      summary: Export a specific check run
  /api/my/checks/{checkId}/runs/{runId}/history:
    get:
      description: Get the history of events for a specific run of a check
      operationId: getMyCheckRunHistory
      parameters:
        - description: The ID for the checkId.
          in: path
          name: checkId
          required: true
          schema:
            type: string
        - description: The ID for the runId.
          in: path
          name: runId
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMyCheckRunHistory'
          description: Successful response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: An unexpected error occurred.
      summary: Get the history of events for a specific run of a check
  /api/my/checks/{checkId}/runs/{runId}/logs:
    get:
      description: Start or Stop logs for a specific check run and get the log channel
      operationId: myCheckLogs
      parameters:
        - description: The ID for the checkId.
          in: path
          name: checkId
          required: true
          schema:
            type: string
        - description: The ID for the runId.
          in: path
          name: runId
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChecksLogsRequestResponse'
          description: Successful response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: An unexpected error occurred.
      summary: Start or Stop logs for a specific check run
  /api/my/checks/{checkId}/runs/{runId}/rerun:
    post:
      description: Re-run a specific check run
      operationId: rerunMyCheck
      parameters:
        - description: The ID for the checkId.
          in: path
          name: checkId
          required: true
          schema:
            type: string
        - description: The ID for the runId.
          in: path
          name: runId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReRunCheckRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReRunCheckRequestResponse'
          description: Successful response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: An unexpected error occurred.
      summary: Re-run a specific check run
  /api/my/checks/{checkId}/runs/{runId}/terminate:
    post:
      description: Terminate a specific check run
      operationId: terminateMyCheckRun
      parameters:
        - description: The ID for the checkId.
          in: path
          name: checkId
          required: true
          schema:
            type: string
        - description: The ID for the runId.
          in: path
          name: runId
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TerminateMyCheckRunRequestResponse'
          description: Successful response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
          description: An unexpected error occurred.
      summary: Terminate a specific check run
servers:
  - description: Demo server
    url: https://demo.credimi.io
  - description: Localhost server
    url: http://localhost:8090/
