variant_order:
  - credential_format
  - client_id_scheme
  - request_method
  - response_mode

variant_keys:
  credential_format:
    - sd_jwt_vc
    - iso_mdl
  client_id_scheme:
    - did
    - pre_registered
    - redirect_uri
    - x509_san_dns
  request_method:
    - request_uri_signed
    - request_uri_unsigned
  response_mode:
    - direct_post
    - direct_post.jwt
    - w3c_dc_api
    - w3c_dc_api.jwt

optional_fields:
  client:
    jwks:
      values:
        client_id_scheme:
          - x509_san_dns
      template: >
        {{
            credimi `
              {
                "credimi_id": "oid_client_jwks",
                "field_id": "jwks",
                "field_label": "i18n_jwks",
                "field_description": "i18n_jwks_description",
                "field_default_value": "{\"keys\":[{\"kty\":\"EC\",\"alg\":\"ES256\",\"crv\":\"P-256\",\"d\":\"q7hdBRr1PiXNqy9SRXVU8zHJPLthQR2ckomdsngeXKc\",\"x\":\"9u3DxePiwDiRR0B2cNo1P0DZsHgOts7zyFqHNcRJDMQ\",\"y\":\"aHspcI5Ug5Xyc5nByxd0O2TcJwYJbXgnaiiIPeGFB94\",\"x5c\":[\"MIIBkDCCATWgAwIBAgIUZDBMNTEQs6qbrNaFnk2GWvOtVwowCgYIKoZIzj0EAwIwHTEbMBkGA1UEAwwSY2xpZW50LmV4YW1wbGUuY29tMB4XDTI1MDcyODEyNTg0OFoXDTI4MDQyMzEyNTg0OFowHTEbMBkGA1UEAwwSY2xpZW50LmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE9u3DxePiwDiRR0B2cNo1P0DZsHgOts7zyFqHNcRJDMRoeylwjlSDlfJzmcHLF3Q7ZNwnBglteCdqKIg94YUH3qNTMFEwHQYDVR0OBBYEFCzPdCbvBoZcb34Tyc1aeJ1OkELzMB8GA1UdIwQYMBaAFCzPdCbvBoZcb34Tyc1aeJ1OkELzMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSQAwRgIhAJSHxJBLBPUicUTB2rNQ5l3SHL2R7yZDanoYozMzI3VbAiEA4ZrbuOpoo903E4Fzul+zkWNN5nqUMHM0+sIXEg8DWaA=\"]}]}",
                "field_type": "object",
                "field_options": []
              }
        `}}

    client_id:
      values:
        client_id_scheme:
          - did
          - pre_registered
          - x509_san_dns
      template: >
        {{
            credimi `
              {
                "credimi_id": "oid_client_id",
                "field_id": "client_id",
                "field_label": "i18n_client_id",
                "field_description": "i18n_client_id_description",
                "field_default_value": "did:web:app.altme.io:issuer",
                "field_type": "string",
                "field_options": []
              }
        `}}

    authorization_encrypted_response_enc:
      values:
        response_mode:
          - direct_post.jwt
          - w3c_dc_api.jwt
      template: >
        {{
            credimi `
              {
                "credimi_id": "oid_authorization_encrypted_response_enc",
                "field_id": "authorization_encrypted_response_enc",
                "field_label": "i18n_authorization_encrypted_response_enc",
                "field_description": "i18n_authorization_encrypted_response_enc_description",
                "field_default_value": "",
                "field_type": "string",
                "field_options": []
              }
        `}}
    authorization_encrypted_response_alg:
      values:
        response_mode:
          - direct_post.jwt
          - w3c_dc_api.jwt
      template: >
        {{
            credimi `
              {
              "credimi_id": "oid_authorization_encrypted_response_alg",
                "field_id": "authorization_encrypted_response_alg",
                "field_label": "i18n_authorization_encrypted_response_alg",
                "field_description": "i18n_authorization_encrypted_response_alg_description",
                "field_default_value": "",
                "field_type": "string",
                "field_options": []
              }
        `}}
