// SPDX-FileCopyrightText: 2026 Forkbomb BV
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// Command fcaf-taxonomy-gen emits Go and TypeScript tables from taxonomy.json.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

type category struct {
	Code  string `json:"code"`
	Label string `json:"label"`
}

type taxonomyFile struct {
	Categories     []category        `json:"categories"`
	SubgroupLabels map[string]string `json:"subgroup_labels"`
}

type genData struct {
	Categories     []category
	SubgroupKeys   []string
	SubgroupLabels map[string]string
}

func main() {
	repoRoot := flag.String("repo-root", ".", "repository root")
	flag.Parse()

	if err := run(*repoRoot); err != nil {
		fmt.Fprintf(os.Stderr, "fcaf-taxonomy-gen: %v\n", err)
		os.Exit(1)
	}
}

func run(repoRoot string) error {
	sourcePath := filepath.Join(repoRoot, "pkg", "fcaf", "taxonomy", "taxonomy.json")
	goOut := filepath.Join(repoRoot, "pkg", "fcaf", "taxonomy", "taxonomy_data.generated.go")
	tsOut := filepath.Join(repoRoot, "webapp", "src", "lib", "fcaf", "taxonomy.generated.ts")

	raw, err := os.ReadFile(sourcePath)
	if err != nil {
		return fmt.Errorf("read taxonomy: %w", err)
	}
	var source taxonomyFile
	if err := json.Unmarshal(raw, &source); err != nil {
		return fmt.Errorf("decode taxonomy: %w", err)
	}
	if err := validate(source); err != nil {
		return err
	}

	data := genData{
		Categories:     source.Categories,
		SubgroupLabels: source.SubgroupLabels,
		SubgroupKeys:   sortedKeys(source.SubgroupLabels),
	}

	goSrc, err := render(goTemplate, data)
	if err != nil {
		return fmt.Errorf("render go: %w", err)
	}
	formattedGo, err := format.Source(goSrc)
	if err != nil {
		return fmt.Errorf("gofmt generated go: %w", err)
	}
	tsSrc, err := render(tsTemplate, data)
	if err != nil {
		return fmt.Errorf("render ts: %w", err)
	}

	if err := os.WriteFile(goOut, formattedGo, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", goOut, err)
	}
	if err := os.WriteFile(tsOut, tsSrc, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", tsOut, err)
	}
	fmt.Printf("generated %s\n", goOut)
	fmt.Printf("generated %s\n", tsOut)
	return nil
}

func validate(source taxonomyFile) error {
	if len(source.Categories) == 0 {
		return fmt.Errorf("taxonomy: categories must not be empty")
	}
	seen := map[string]struct{}{}
	hasOther := false
	for _, cat := range source.Categories {
		if cat.Code == "" || cat.Label == "" {
			return fmt.Errorf("taxonomy: category requires code and label")
		}
		if _, ok := seen[cat.Code]; ok {
			return fmt.Errorf("taxonomy: duplicate category code %q", cat.Code)
		}
		seen[cat.Code] = struct{}{}
		if cat.Code == "OTHER" {
			hasOther = true
		}
	}
	if !hasOther {
		return fmt.Errorf("taxonomy: categories must include OTHER")
	}
	if len(source.SubgroupLabels) == 0 {
		return fmt.Errorf("taxonomy: subgroup_labels must not be empty")
	}
	for key, label := range source.SubgroupLabels {
		if key != strings.ToLower(key) {
			return fmt.Errorf("taxonomy: subgroup key %q must be lowercase", key)
		}
		if label == "" {
			return fmt.Errorf("taxonomy: subgroup %q has empty label", key)
		}
	}
	return nil
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func render(tmpl string, data genData) ([]byte, error) {
	t, err := template.New("out").Funcs(template.FuncMap{
		"goString": strconvQuote,
		"tsString": strconvQuote,
	}).Parse(tmpl)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func strconvQuote(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

const goTemplate = `// SPDX-FileCopyrightText: 2026 Forkbomb BV
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by fcaf-taxonomy-gen; DO NOT EDIT.

package taxonomy

// CategoryOrder is the canonical display order for FCAF areas.
var CategoryOrder = []string{
{{- range .Categories }}
	{{ goString .Code }},
{{- end }}
}

// Categories maps category codes to display labels.
var Categories = map[string]Category{
{{- range .Categories }}
	{{ goString .Code }}: {Code: {{ goString .Code }}, Label: {{ goString .Label }}},
{{- end }}
}

// SubgroupLabels maps normalized (lowercased) subgroup keys to display labels.
var SubgroupLabels = map[string]string{
{{- range .SubgroupKeys }}
	{{ goString . }}: {{ goString (index $.SubgroupLabels .) }},
{{- end }}
}
`

const tsTemplate = `// SPDX-FileCopyrightText: 2026 Forkbomb BV
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by fcaf-taxonomy-gen; DO NOT EDIT.

export const FCAF_CATEGORY_ORDER = [
{{- range .Categories }}
	{{ tsString .Code }},
{{- end }}
] as const;

export type FCAFCategoryCode = (typeof FCAF_CATEGORY_ORDER)[number];

export const FCAF_CATEGORY_LABELS: Record<FCAFCategoryCode, string> = {
{{- range .Categories }}
	{{ tsString .Code }}: {{ tsString .Label }},
{{- end }}
};

export const FCAF_SUBGROUP_LABELS: Record<string, string> = {
{{- range .SubgroupKeys }}
	{{ tsString . }}: {{ tsString (index $.SubgroupLabels .) }},
{{- end }}
};
`
