// SPDX-FileCopyrightText: 2026 Forkbomb BV
//
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * GENERATED by go generate ./pkg/conformancecatalog — do not edit by hand.
 * Injected into index.generated.ts by generate.catalog-pb-types.ts
 * (Response aliases that need BaseSystemFields are added at inject time).
 * Source of truth: pkg/conformancecatalog/schema.go (Client=true columns).
 */

export type ConformanceChecksRecord = {
	id: string
	path: string
	title: string
	standard: string
	version: string
	suite: string
	file: string
	visible_in?: string[]
	protocol?: string
	sut?: string
	role?: string
	provider?: string
	norm_standard?: string
	component?: string
	norm_version?: string
}

export type ConformanceSuitesRecord = {
	id: string
	standard: string
	component?: string
	component_rank?: number
	version?: string
	suite: string
	provider?: string
	suite_name?: string
	suite_homepage?: string
	suite_repository?: string
	suite_help?: string
	suite_description?: string
	suite_logo?: string
	check_count: number
	check_paths?: string[]
	check_titles?: string[]
	check_files?: string[]
	visible_in?: string[]
	fs_standard: string
	fs_version: string
	path_prefix: string
}
