/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OpenidCredentialIssuerSchema {
  /**
   * The Credential Issuer's identifier
   */
  credential_issuer: string;
  /**
   * Array of OAuth 2.0 Authorization Server identifiers.
   */
  authorization_servers?: string[];
  /**
   * URL of the Credential Issuer's Credential Endpoint.
   */
  credential_endpoint: string;
  /**
   * URL of the Credential Issuer's Nonce Endpoint.
   */
  nonce_endpoint?: string;
  /**
   * URL of the Credential Issuer's Deferred Credential Endpoint.
   */
  deferred_credential_endpoint?: string;
  /**
   * URL of the Credential Issuer's Notification Endpoint.
   */
  notification_endpoint?: string;
  credential_response_encryption?: {
    alg_values_supported: (
      | "HS256"
      | "HS384"
      | "HS512"
      | "RS256"
      | "RS384"
      | "RS512"
      | "ES256"
      | "ES384"
      | "ES512"
      | "PS256"
      | "PS384"
      | "PS512"
      | "none"
      | "RSA1_5"
      | "RSA-OAEP"
      | "RSA-OAEP-256"
      | "A128KW"
      | "A192KW"
      | "A256KW"
      | "dir"
      | "ECDH-ES"
      | "ECDH-ES+A128KW"
      | "ECDH-ES+A192KW"
      | "ECDH-ES+A256KW"
      | "A128GCMKW"
      | "A192GCMKW"
      | "A256GCMKW"
      | "PBES2-HS256+A128KW"
      | "PBES2-HS384+A192KW"
      | "PBES2-HS512+A256KW"
      | "EdDSA"
      | "RSA-OAEP-384"
      | "RSA-OAEP-512"
      | "ES256K"
      | "ML-DSA-44"
      | "ML-DSA-65"
      | "ML-DSA-87"
    )[];
    enc_values_supported: ("A128CBC-HS256" | "A128GCM" | "A192CBC-HS384" | "A192GCM" | "A256CBC-HS512" | "A256GCM")[];
    encryption_required: boolean;
    [k: string]: unknown;
  };
  batch_credential_issuance?: {
    batch_size: number;
    [k: string]: unknown;
  };
  /**
   * JWT containing Credential Issuer metadata parameters as claims.
   */
  signed_metadata?: string;
  display?: {
    name?: string;
    locale?: string;
    logo?: {
      uri: string;
      alt_text?: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  credential_configurations_supported: {
    [k: string]: {
      format: string;
      scope?: string;
      cryptographic_binding_methods_supported?: ((
        | {
            [k: string]: unknown;
          }
        | ("jwk" | "JWK" | "cose_key")
      ) &
        string)[];
      credential_signing_alg_values_supported?: (
        | "ES256"
        | "EdDSA"
        | "Ed25519Signature2020"
        | "RS256"
        | "ES256K"
        | "RSA"
        | "RsaSignature2018"
      )[];
      proof_types_supported?: {
        [k: string]: {
          proof_signing_alg_values_supported: ("ES256" | "ES384" | "EdDSA" | "PS256" | "RS256")[];
          key_attestations_required?: {
            key_storage?: string[];
            user_authentication?: string[];
            [k: string]: unknown;
          };
          [k: string]: unknown;
        };
      };
      display?: {
        name: string;
        locale?: string;
        logo?: {
          [k: string]: unknown;
        };
        [k: string]: unknown;
      }[];
      credential_definition?: {
        type?: string[];
        credentialSubject?: {
          [k: string]: {
            mandatory?: boolean;
            display?: {
              name: string;
              locale?: string;
              [k: string]: unknown;
            }[];
            [k: string]: unknown;
          };
        };
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
  };
  [k: string]: unknown;
}
