// SPDX-FileCopyrightText: 2026 Forkbomb BV
//
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * GENERATED by go generate ./pkg/conformancecatalog — do not edit by hand.
 * Source of truth: pkg/conformancecatalog/schema.go (Client=true columns).
 */

export const CHECK_CLIENT_COLUMNS = [
	'id',
	'path',
	'title',
	'fs_standard',
	'fs_version',
	'suite',
	'file',
	'visible_in',
	'protocol',
	'sut',
	'role',
	'provider',
	'standard',
	'component',
	'version',
] as const;

export type CheckClientColumn = (typeof CHECK_CLIENT_COLUMNS)[number];

export const SUITE_CLIENT_COLUMNS = [
	'id',
	'standard',
	'component',
	'component_rank',
	'version',
	'suite',
	'provider',
	'suite_name',
	'suite_homepage',
	'suite_repository',
	'suite_help',
	'suite_description',
	'suite_logo',
	'check_count',
	'members',
	'visible_in',
	'fs_standard',
	'fs_version',
	'path_prefix',
] as const;

export type SuiteClientColumn = (typeof SUITE_CLIENT_COLUMNS)[number];
