// SPDX-FileCopyrightText: 2026 Forkbomb BV
//
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * GENERATED by go generate ./pkg/conformancecatalog — do not edit by hand.
 * Source of truth: pkg/conformancecatalog/schema.go (Client=true columns).
 * Kind + optional + Default drive Zod (record.schemas.ts).
 * pbType is the PocketBase CollectionField type for synthetic CollectionModel
 * stubs (generate.collections-models.ts stitches; it does not re-map Kind).
 */

export type CatalogColumnPbType = 'text' | 'number' | 'json';

export type CatalogColumnKind =
	| 'string'
	| 'int'
	| 'nonNegInt'
	| 'stringArray'
	| 'memberArray';

export const CHECK_CLIENT_COLUMN_SPECS = [
	{ name: 'id', kind: 'string', optional: false, pbType: 'text' },
	{ name: 'path', kind: 'string', optional: false, pbType: 'text' },
	{ name: 'title', kind: 'string', optional: false, pbType: 'text' },
	{ name: 'fs_standard', kind: 'string', optional: false, pbType: 'text' },
	{ name: 'fs_version', kind: 'string', optional: false, pbType: 'text' },
	{ name: 'suite', kind: 'string', optional: false, pbType: 'text' },
	{ name: 'file', kind: 'string', optional: false, pbType: 'text' },
	{ name: 'visible_in', kind: 'stringArray', optional: true, pbType: 'json' },
	{ name: 'protocol', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'sut', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'role', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'provider', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'standard', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'component', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'version', kind: 'string', optional: true, pbType: 'text' },
] as const;

export type CheckClientColumn = (typeof CHECK_CLIENT_COLUMN_SPECS)[number]['name'];

export const CHECK_CLIENT_COLUMNS: readonly CheckClientColumn[] = CHECK_CLIENT_COLUMN_SPECS.map((c) => c.name);

export const SUITE_CLIENT_COLUMN_SPECS = [
	{ name: 'id', kind: 'string', optional: false, pbType: 'text' },
	{ name: 'standard', kind: 'string', optional: false, pbType: 'text' },
	{ name: 'component', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'component_rank', kind: 'nonNegInt', optional: true, pbType: 'number' },
	{ name: 'version', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'suite', kind: 'string', optional: false, pbType: 'text' },
	{ name: 'provider', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'provider_label', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'suite_name', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'suite_subtitle', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'suite_homepage', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'suite_repository', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'suite_help', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'suite_description', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'suite_logo', kind: 'string', optional: true, pbType: 'text' },
	{ name: 'check_count', kind: 'nonNegInt', optional: false, pbType: 'number' },
	{ name: 'members', kind: 'memberArray', optional: true, pbType: 'json' },
	{ name: 'visible_in', kind: 'stringArray', optional: true, pbType: 'json' },
	{ name: 'fs_standard', kind: 'string', optional: false, pbType: 'text' },
	{ name: 'fs_version', kind: 'string', optional: false, pbType: 'text' },
	{ name: 'path_prefix', kind: 'string', optional: false, pbType: 'text' },
] as const;

export type SuiteClientColumn = (typeof SUITE_CLIENT_COLUMN_SPECS)[number]['name'];

export const SUITE_CLIENT_COLUMNS: readonly SuiteClientColumn[] = SUITE_CLIENT_COLUMN_SPECS.map((c) => c.name);
