<!--
SPDX-FileCopyrightText: 2025 Forkbomb BV

SPDX-License-Identifier: AGPL-3.0-or-later
-->

<script lang="ts" module>
	export type FieldMode = 'default' | 'static' | 'dynamic';
</script>

<script lang="ts">
	import { createIntentUrl } from '$lib/credentials';
	import { fromStore } from 'svelte/store';
	import { stringProxy, type SuperForm } from 'sveltekit-superforms';

	import type { CredentialIssuersResponse, CredentialsRecord } from '@/pocketbase/types';

	import T from '@/components/ui-custom/t.svelte';
	import * as Tabs from '@/components/ui/tabs';
	import Field from '@/forms/fields/field.svelte';
	import { QrCode } from '@/qr';

	import DynamicTab from './dynamic-tab.svelte';

	//

	interface Props {
		form: SuperForm<{ deeplink: string; yaml: string }>;
		credential?: CredentialsRecord;
		credentialIssuer: CredentialIssuersResponse;
		activeTab: FieldMode;
	}

	let { form, credential, credentialIssuer, activeTab = $bindable('default') }: Props = $props();

	/* Field value */

	const deeplinkState = fromStore(stringProxy(form, 'deeplink', { empty: 'undefined' }));

	/* Tabs */

	const modesTabs = {
		default: { label: 'Default', value: 'default' },
		static: { label: 'Static', value: 'static' },
		dynamic: { label: 'Dynamic', value: 'dynamic' }
	} satisfies Record<FieldMode, { label: string; value: FieldMode }>;

	/* Default */

	const defaultQr = $derived.by(() => {
		try {
			if (credential) {
				return createIntentUrl(credential, credentialIssuer.url);
			}
			return undefined;
		} catch (error) {
			console.error(error);
			return undefined;
		}
	});

	const isDefaultDisabled = $derived.by(() => {
		return !credential || !credential.key;
	});

	$effect(() => {
		if (credential?.yaml) {
			activeTab = 'dynamic';
		} else if (credential?.deeplink) {
			activeTab = 'static';
		} else if (!isDefaultDisabled) {
			activeTab = 'default';
		}
	});

	//

	const qrProps = {
		cellSize: 10,
		class: 'size-60 rounded-md border aspect-square'
	};
</script>

<Tabs.Root bind:value={activeTab} class="w-full">
	<Tabs.List class="mb-4 grid w-full grid-cols-3">
		{#each Object.values(modesTabs) as tab}
			<Tabs.Trigger value={tab.value} disabled={tab.value === 'default' && isDefaultDisabled}>
				{tab.label}
			</Tabs.Trigger>
		{/each}
	</Tabs.List>

	<Tabs.Content value={modesTabs.default.value}>
		{#if defaultQr}
			<div class="flex gap-4">
				<div>
					<T class="mb-3">Autogenerated deeplink:</T>
					<a
						href={defaultQr}
						target="_blank"
						class="block break-all text-xs leading-5 underline">{defaultQr}</a
					>
				</div>
				<QrCode src={defaultQr} {...qrProps} />
			</div>
		{/if}
	</Tabs.Content>

	<Tabs.Content value={modesTabs.static.value}>
		<div class="flex gap-4">
			<div class="grow">
				<T class="mb-3">Configure a static deeplink with fixed parameters.</T>
				<Field
					{form}
					name="deeplink"
					options={{ placeholder: 'e.g. openid-credential-offer://?...' }}
				/>
			</div>
			<div class={qrProps.class}>
				{#if deeplinkState.current}
					<QrCode src={deeplinkState.current ?? ''} {...qrProps} />
				{:else}
					<div
						class="text-muted-foreground flex aspect-square items-center justify-center p-4"
					>
						Type to generate a QR code
					</div>
				{/if}
			</div>
		</div>
	</Tabs.Content>

	<Tabs.Content value="dynamic" class="mt-4 min-w-0">
		<T>
			Configure the YAML below to generate a dynamic credential offer with runtime parameters.
		</T>
		<div class="min-w-0">
			<DynamicTab {form} />
		</div>
	</Tabs.Content>
</Tabs.Root>

<!-- <FieldWrapper field={deeplinkName} {options}>
		{#snippet children()}
			{#if activeTab === 'static' && staticDeepLink}
				<div class="mb-6">
					<div class="mb-3 flex items-center gap-2 text-sm">
						<div
							class="h-2 w-2 rounded-full {qrStatus().variant === 'success'
								? 'bg-green-500'
								: qrStatus().variant === 'destructive'
									? 'bg-red-500'
									: 'bg-blue-500'}"
						></div>
						<span class="text-muted-foreground">{qrStatus().message}</span>
					</div>
					<QrDisplay src={staticDeepLink} showUrl={staticShowUrl} />
				</div>
			{:else if activeTab === 'dynamic' && credentialOffer}
				<div class="mb-6">
					<div class="mb-3 flex items-center gap-2 text-sm">
						<div
							class="h-2 w-2 rounded-full {qrStatus().variant === 'success'
								? 'bg-green-500'
								: qrStatus().variant === 'destructive'
									? 'bg-red-500'
									: 'bg-blue-500'}"
						></div>
						<span class="text-muted-foreground">{qrStatus().message}</span>
					</div>
					<QrDisplay src={credentialOffer} />
				</div>
			{:else}
				<div class="mb-6">
					<div class="mb-3 flex items-center gap-2 text-sm">
						<div
							class="h-2 w-2 rounded-full {qrStatus().variant === 'success'
								? 'bg-green-500'
								: qrStatus().variant === 'destructive'
									? 'bg-red-500'
									: 'bg-blue-500'}"
						></div>
						<span class="text-muted-foreground">{qrStatus().message}</span>
					</div>
					<div
						class="border-muted-foreground/25 bg-muted/10 flex h-60 w-60 items-center justify-center rounded-md border border-dashed"
					>
						<span class="text-muted-foreground text-sm">QR code will appear here</span>
					</div>
				</div>
			{/if}

			<Tabs.Root bind:value={activeTab} class="w-full">
				<Tabs.List class="grid w-full grid-cols-2">
					<Tabs.Trigger value="static">{staticTabLabel()}</Tabs.Trigger>
					<Tabs.Trigger value="dynamic">{dynamicTabLabel()}</Tabs.Trigger>
				</Tabs.List>

				<Tabs.Content value="static" class="mt-4">
					<div class="mb-3 text-sm">
						{#if staticShowUrl === false}
							You've configured a custom deeplink. Clear the field below to use the
							default configuration.
						{:else}
							Pre-configured credential offer with fixed parameters. Enter a custom
							deeplink below to override.
						{/if}
					</div>
					<StaticTab
						{form}
						name={deeplinkName}
						{credential}
						{credentialIssuer}
						{options}
						onDeepLinkChange={(deepLink, showUrl) => {
							if (!deepLink) return;
							staticDeepLink = deepLink;
							staticShowUrl = showUrl;
						}}
					/>
				</Tabs.Content>

				<Tabs.Content value="dynamic" class="mt-4 min-w-0">
					<div class="text-muted-foreground mb-3 text-sm">
						{#if credentialOffer}
							QR code generated successfully from your YAML configuration.
						{:else}
							Configure the YAML below to generate a dynamic credential offer with
							runtime parameters.
						{/if}
					</div>
					<div class="min-w-0">
						<DynamicTab
							{form}
							name={yaml}
							bind:isSubmittingCompliance
							bind:credentialOffer
							bind:workflowSteps
							bind:workflowOutput
							bind:workflowError
						/>
					</div>
				</Tabs.Content>
			</Tabs.Root>
		{/snippet}
	</FieldWrapper> -->
