// SPDX-FileCopyrightText: 2026 Forkbomb BV
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by fcaf-taxonomy-gen; DO NOT EDIT.

package taxonomy

// CategoryOrder is the canonical display order for FCAF areas.
var CategoryOrder = []string{
	"DM",
	"MS",
	"IA",
	"SM",
	"SH",
	"UC",
	"OTHER",
}

// Categories maps category codes to display labels.
var Categories = map[string]Category{
	"DM":    {Code: "DM", Label: "Data model"},
	"MS":    {Code: "MS", Label: "Message structure"},
	"IA":    {Code: "IA", Label: "Interaction"},
	"SM":    {Code: "SM", Label: "Security mechanisms"},
	"SH":    {Code: "SH", Label: "Shared"},
	"UC":    {Code: "UC", Label: "Use cases"},
	"OTHER": {Code: "OTHER", Label: "Other"},
}

// SubgroupLabels maps normalized (lowercased) subgroup keys to display labels.
var SubgroupLabels = map[string]string{
	"addressdata":        "Address data",
	"credentialformats":  "Credential formats",
	"credentialmetadata": "Credential metadata",
	"cryptography":       "Cryptography",
	"devicebinding":      "Device binding",
	"encoding":           "Encoding",
	"engagement":         "Engagement",
	"identifyingdata":    "Identifying data",
	"issuerintegrity":    "Issuer integrity",
	"maininteraction":    "Main interaction",
	"metadata":           "Metadata",
	"presentation":       "Presentation",
	"protocolflow":       "Protocol flow",
	"protocolmessages":   "Protocol messages",
	"rpintegrity":        "RP integrity",
	"sessionbinding":     "Session binding",
	"sessionencryption":  "Session encryption",
	"supportive":         "Supportive",
	"trustmechanisms":    "Trust mechanisms",
}
