// SPDX-FileCopyrightText: 2026 Forkbomb BV
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//go:build ignore

// Generates FE catalog wire artifacts from schema.go:
//
//   - webapp/src/lib/conformance/columns.ts
//
//   - webapp/src/lib/conformance/record.schemas.ts
//
//   - webapp/src/modules/pocketbase/types/catalog-pb-records.ts
//
//     go generate ./pkg/conformancecatalog
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"github.com/forkbombeu/credimi/pkg/conformancecatalog"
)

const spdxHeader = `// SPDX-FileCopyrightText: 2026 Forkbomb BV
//
// SPDX-License-Identifier: AGPL-3.0-or-later
`

func main() {
	root := findRepoRoot()
	checks := conformancecatalog.CheckClientColumns()
	suites := conformancecatalog.SuiteClientColumns()

	mustWrite(filepath.Join(root, "webapp", "src", "lib", "conformance", "columns.ts"), columnsTS(checks, suites))
	mustWrite(filepath.Join(root, "webapp", "src", "lib", "conformance", "record.schemas.ts"), recordSchemasTS(checks, suites))
	mustWrite(filepath.Join(root, "webapp", "src", "modules", "pocketbase", "types", "catalog-pb-records.ts"), catalogPBRecordsTS(checks, suites))
}

func columnsTS(checks, suites []conformancecatalog.ClientColumn) string {
	var b bytes.Buffer
	b.WriteString(spdxHeader)
	b.WriteString(`
/**
 * GENERATED by go generate ./pkg/conformancecatalog — do not edit by hand.
 * Source of truth: pkg/conformancecatalog/schema.go (Client=true columns).
 */
`)
	writeNameConst(&b, "CHECK_CLIENT_COLUMNS", "CheckClientColumn", checks)
	writeNameConst(&b, "SUITE_CLIENT_COLUMNS", "SuiteClientColumn", suites)
	return b.String()
}

func recordSchemasTS(checks, suites []conformancecatalog.ClientColumn) string {
	var b bytes.Buffer
	b.WriteString(spdxHeader)
	b.WriteString(`
/**
 * GENERATED by go generate ./pkg/conformancecatalog — do not edit by hand.
 * Source of truth: pkg/conformancecatalog/schema.go (Client=true columns).
 */
import { z } from 'zod';

`)
	writeZodObject(&b, "conformanceCheckRecordSchema", "ConformanceCheckRecord", checks)
	b.WriteByte('\n')
	writeZodObject(&b, "conformanceSuiteRecordSchema", "ConformanceSuiteRecord", suites)
	return b.String()
}

func catalogPBRecordsTS(checks, suites []conformancecatalog.ClientColumn) string {
	var b bytes.Buffer
	b.WriteString(spdxHeader)
	b.WriteString(`
/**
 * GENERATED by go generate ./pkg/conformancecatalog — do not edit by hand.
 * Injected into index.generated.ts by generate.catalog-pb-types.ts
 * (Response aliases that need BaseSystemFields are added at inject time).
 * Source of truth: pkg/conformancecatalog/schema.go (Client=true columns).
 */

export type ConformanceChecksRecord = {
`)
	writeTSFields(&b, checks)
	b.WriteString(`}

export type ConformanceSuitesRecord = {
`)
	writeTSFields(&b, suites)
	b.WriteString(`}
`)
	return b.String()
}

func writeNameConst(b *bytes.Buffer, name, typeName string, cols []conformancecatalog.ClientColumn) {
	b.WriteString(fmt.Sprintf("\nexport const %s = [\n", name))
	for _, c := range cols {
		b.WriteString(fmt.Sprintf("\t'%s',\n", c.Name))
	}
	b.WriteString("] as const;\n\n")
	b.WriteString(fmt.Sprintf("export type %s = (typeof %s)[number];\n", typeName, name))
}

func writeZodObject(b *bytes.Buffer, schemaName, typeName string, cols []conformancecatalog.ClientColumn) {
	b.WriteString(fmt.Sprintf("export const %s = z.object({\n", schemaName))
	for _, c := range cols {
		b.WriteString(fmt.Sprintf("\t%s: %s,\n", c.Name, zodFieldExpr(c)))
	}
	b.WriteString("});\n\n")
	b.WriteString(fmt.Sprintf("export type %s = z.infer<typeof %s>;\n", typeName, schemaName))
}

func zodFieldExpr(c conformancecatalog.ClientColumn) string {
	base := zodBase(c.Kind)
	if !c.Optional {
		return base
	}
	out := base + ".optional()"
	if c.Default != "" {
		out += ".default(" + c.Default + ")"
	}
	return out
}

func zodBase(kind conformancecatalog.ColumnKind) string {
	switch kind {
	case conformancecatalog.ColumnKindString:
		return "z.string()"
	case conformancecatalog.ColumnKindInt:
		return "z.number().int()"
	case conformancecatalog.ColumnKindNonNegInt:
		return "z.number().int().nonnegative()"
	case conformancecatalog.ColumnKindStringArray:
		return "z.array(z.string())"
	case conformancecatalog.ColumnKindMemberArray:
		return "z.array(z.object({ path: z.string(), title: z.string(), file: z.string() }))"
	default:
		panic(fmt.Sprintf("unknown column kind %q", kind))
	}
}

func writeTSFields(b *bytes.Buffer, cols []conformancecatalog.ClientColumn) {
	for _, c := range cols {
		tsType := tsType(c.Kind)
		if c.Optional {
			b.WriteString(fmt.Sprintf("\t%s?: %s\n", c.Name, tsType))
		} else {
			b.WriteString(fmt.Sprintf("\t%s: %s\n", c.Name, tsType))
		}
	}
}

func tsType(kind conformancecatalog.ColumnKind) string {
	switch kind {
	case conformancecatalog.ColumnKindString:
		return "string"
	case conformancecatalog.ColumnKindInt, conformancecatalog.ColumnKindNonNegInt:
		return "number"
	case conformancecatalog.ColumnKindStringArray:
		return "string[]"
	case conformancecatalog.ColumnKindMemberArray:
		return "{ path: string; title: string; file: string }[]"
	default:
		panic(fmt.Sprintf("unknown column kind %q", kind))
	}
}

func mustWrite(path, contents string) {
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
		os.Exit(1)
	}
	fmt.Println("wrote", path)
}

func findRepoRoot() string {
	wd, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	dir := wd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			panic("go.mod not found from " + wd)
		}
		dir = parent
	}
}
