// SPDX-FileCopyrightText: 2026 Forkbomb BV
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//go:build ignore

// Generates webapp/src/lib/conformance/columns.ts from schema.go.
//
//	go generate ./pkg/conformancecatalog
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"github.com/forkbombeu/credimi/pkg/conformancecatalog"
)

func main() {
	root := findRepoRoot()
	outPath := filepath.Join(root, "webapp", "src", "lib", "conformance", "columns.ts")

	var b bytes.Buffer
	b.WriteString(`// SPDX-FileCopyrightText: 2026 Forkbomb BV
//
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * GENERATED by go generate ./pkg/conformancecatalog — do not edit by hand.
 * Source of truth: pkg/conformancecatalog/schema.go (Client=true columns).
 */
`)
	writeConst(&b, "CHECK_CLIENT_COLUMNS", "CheckClientColumn", conformancecatalog.CheckClientColumnNames())
	writeConst(&b, "SUITE_CLIENT_COLUMNS", "SuiteClientColumn", conformancecatalog.SuiteClientColumnNames())

	if err := os.WriteFile(outPath, b.Bytes(), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Println("wrote", outPath)
}

func writeConst(b *bytes.Buffer, name, typeName string, cols []string) {
	b.WriteString(fmt.Sprintf("\nexport const %s = [\n", name))
	for _, c := range cols {
		b.WriteString(fmt.Sprintf("\t'%s',\n", c))
	}
	b.WriteString("] as const;\n\n")
	b.WriteString(fmt.Sprintf("export type %s = (typeof %s)[number];\n", typeName, name))
}

func findRepoRoot() string {
	wd, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	dir := wd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			panic("go.mod not found from " + wd)
		}
		dir = parent
	}
}
