// SPDX-FileCopyrightText: 2026 Forkbomb BV
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//go:build ignore

// Generates catalog wire artifacts from schema.go:
//
//   - pkg/conformancecatalog/records_gen.go (Check / SuiteRecord)
//
//   - webapp/src/lib/conformance/columns.ts
//
//   - webapp/src/lib/conformance/record.schemas.ts
//
//   - webapp/src/modules/pocketbase/types/catalog-pb-records.ts
//
//     go generate ./pkg/conformancecatalog
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/forkbombeu/credimi/pkg/conformancecatalog"
)

const spdxHeader = `// SPDX-FileCopyrightText: 2026 Forkbomb BV
//
// SPDX-License-Identifier: AGPL-3.0-or-later
`

func main() {
	root := findRepoRoot()
	checks := conformancecatalog.CheckClientColumns()
	suites := conformancecatalog.SuiteClientColumns()
	checkGrain := conformancecatalog.CheckGrainColumns()
	suiteGrain := conformancecatalog.SuiteGrainColumns()

	mustWrite(filepath.Join(root, "pkg", "conformancecatalog", "records_gen.go"), recordsGo(checkGrain, suiteGrain))
	mustWrite(filepath.Join(root, "webapp", "src", "lib", "conformance", "columns.ts"), columnsTS(checks, suites))
	mustWrite(filepath.Join(root, "webapp", "src", "lib", "conformance", "record.schemas.ts"), recordSchemasTS(checks, suites))
	mustWrite(filepath.Join(root, "webapp", "src", "modules", "pocketbase", "types", "catalog-pb-records.ts"), catalogPBRecordsTS(checks, suites))
}

func recordsGo(checks, suites []conformancecatalog.GrainColumn) string {
	var b bytes.Buffer
	b.WriteString(spdxHeader)
	b.WriteString(`
// Code generated by go generate ./pkg/conformancecatalog; DO NOT EDIT.
// Source of truth: schema.go columnSpec (ADR-0009).

package conformancecatalog

`)
	writeGoStruct(&b, "Check", `Check is one catalog entry derived from a template file.
// Lean check grain: path, title, facets, and identity only. Suite display
// metadata (name, logo, URLs) lives on the suite projection (ADR-0002).
// Generated from checkColumns; HTTP list/get wraps it in checkHTTPRecord.`, checks)
	b.WriteByte('\n')
	writeGoStruct(&b, "SuiteRecord", `SuiteRecord is one hub-table row: a suite under normalized standard×component×version.
// FS* fields preserve durable path identity for hub links; Standard/Component/Version
// are the product projection.
// Generated from suiteColumns; HTTP list/get wraps it in suiteHTTPRecord.`, suites)
	return b.String()
}

func writeGoStruct(b *bytes.Buffer, typeName, doc string, cols []conformancecatalog.GrainColumn) {
	b.WriteString("// " + doc + "\n")
	b.WriteString(fmt.Sprintf("type %s struct {\n", typeName))
	maxField := 0
	maxType := 0
	fields := make([]goField, len(cols))
	for i, c := range cols {
		f := goField{
			name: exportedFieldName(c.Name),
			typ:  goType(c.Kind),
			db:   c.Name,
			json: c.Name,
		}
		fields[i] = f
		if len(f.name) > maxField {
			maxField = len(f.name)
		}
		if len(f.typ) > maxType {
			maxType = len(f.typ)
		}
	}
	for _, f := range fields {
		b.WriteString(fmt.Sprintf("\t%-*s %-*s `db:%q json:%q`\n",
			maxField, f.name, maxType, f.typ, f.db, f.json))
	}
	b.WriteString("}\n")
}

type goField struct {
	name, typ, db, json string
}

func exportedFieldName(col string) string {
	parts := strings.Split(col, "_")
	var b strings.Builder
	for _, p := range parts {
		switch strings.ToLower(p) {
		case "id":
			b.WriteString("ID")
		case "fs":
			b.WriteString("FS")
		case "sut":
			b.WriteString("SUT")
		default:
			if p == "" {
				continue
			}
			b.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	return b.String()
}

func goType(kind conformancecatalog.ColumnKind) string {
	switch kind {
	case conformancecatalog.ColumnKindString:
		return "string"
	case conformancecatalog.ColumnKindInt, conformancecatalog.ColumnKindNonNegInt:
		return "int"
	case conformancecatalog.ColumnKindStringArray:
		return "stringArray"
	case conformancecatalog.ColumnKindMemberArray:
		return "memberArray"
	default:
		panic(fmt.Sprintf("unknown column kind %q", kind))
	}
}

func columnsTS(checks, suites []conformancecatalog.ClientColumn) string {
	var b bytes.Buffer
	b.WriteString(spdxHeader)
	b.WriteString(`
/**
 * GENERATED by go generate ./pkg/conformancecatalog — do not edit by hand.
 * Source of truth: pkg/conformancecatalog/schema.go (Client=true columns).
 * Kind + optional + Default drive Zod (record.schemas.ts).
 * pbType is the PocketBase CollectionField type for synthetic CollectionModel
 * stubs (generate.collections-models.ts stitches; it does not re-map Kind).
 */

export type CatalogColumnPbType = 'text' | 'number' | 'json';

export type CatalogColumnKind =
	| 'string'
	| 'int'
	| 'nonNegInt'
	| 'stringArray'
	| 'memberArray';
`)
	writeColumnSpecs(&b, "CHECK_CLIENT_COLUMN_SPECS", "CHECK_CLIENT_COLUMNS", "CheckClientColumn", checks)
	writeColumnSpecs(&b, "SUITE_CLIENT_COLUMN_SPECS", "SUITE_CLIENT_COLUMNS", "SuiteClientColumn", suites)
	return b.String()
}

func recordSchemasTS(checks, suites []conformancecatalog.ClientColumn) string {
	var b bytes.Buffer
	b.WriteString(spdxHeader)
	b.WriteString(`
/**
 * GENERATED by go generate ./pkg/conformancecatalog — do not edit by hand.
 * Source of truth: pkg/conformancecatalog/schema.go (Client=true columns).
 */
import { z } from 'zod';

`)
	writeZodObject(&b, "conformanceCheckRecordSchema", "ConformanceCheckRecord", checks)
	b.WriteByte('\n')
	writeZodObject(&b, "conformanceSuiteRecordSchema", "ConformanceSuiteRecord", suites)
	return b.String()
}

func catalogPBRecordsTS(checks, suites []conformancecatalog.ClientColumn) string {
	var b bytes.Buffer
	b.WriteString(spdxHeader)
	b.WriteString(`
/**
 * GENERATED by go generate ./pkg/conformancecatalog — do not edit by hand.
 * Injected into index.generated.ts by generate.catalog-pb-types.ts
 * (Response aliases that need BaseSystemFields are added at inject time).
 * Source of truth: pkg/conformancecatalog/schema.go (Client=true columns).
 */

export type ConformanceChecksRecord = {
`)
	writeTSFields(&b, checks)
	b.WriteString(`}

export type ConformanceSuitesRecord = {
`)
	writeTSFields(&b, suites)
	b.WriteString(`}
`)
	return b.String()
}

func writeColumnSpecs(b *bytes.Buffer, specsName, namesName, typeName string, cols []conformancecatalog.ClientColumn) {
	b.WriteString(fmt.Sprintf("\nexport const %s = [\n", specsName))
	for _, c := range cols {
		b.WriteString(fmt.Sprintf(
			"\t{ name: '%s', kind: '%s', optional: %t, pbType: '%s' },\n",
			c.Name, c.Kind, c.Optional, pbType(c.Kind),
		))
	}
	b.WriteString("] as const;\n\n")
	b.WriteString(fmt.Sprintf("export type %s = (typeof %s)[number]['name'];\n\n", typeName, specsName))
	b.WriteString(fmt.Sprintf(
		"export const %s: readonly %s[] = %s.map((c) => c.name);\n",
		namesName, typeName, specsName,
	))
}

// pbType is the PocketBase CollectionField type for a Client column Kind.
func pbType(kind conformancecatalog.ColumnKind) string {
	switch kind {
	case conformancecatalog.ColumnKindString:
		return "text"
	case conformancecatalog.ColumnKindInt, conformancecatalog.ColumnKindNonNegInt:
		return "number"
	case conformancecatalog.ColumnKindStringArray, conformancecatalog.ColumnKindMemberArray:
		return "json"
	default:
		panic(fmt.Sprintf("unknown column kind %q", kind))
	}
}

func writeZodObject(b *bytes.Buffer, schemaName, typeName string, cols []conformancecatalog.ClientColumn) {
	b.WriteString(fmt.Sprintf("export const %s = z.object({\n", schemaName))
	for _, c := range cols {
		b.WriteString(fmt.Sprintf("\t%s: %s,\n", c.Name, zodFieldExpr(c)))
	}
	b.WriteString("});\n\n")
	b.WriteString(fmt.Sprintf("export type %s = z.infer<typeof %s>;\n", typeName, schemaName))
}

func zodFieldExpr(c conformancecatalog.ClientColumn) string {
	base := zodBase(c.Kind)
	if !c.Optional {
		return base
	}
	out := base + ".optional()"
	if c.Default != "" {
		out += ".default(" + c.Default + ")"
	}
	return out
}

// memberArray wire shape (Zod + TS); one place for path/title/file members.
const (
	memberArrayZod = "z.array(z.object({ path: z.string(), title: z.string(), file: z.string() }))"
	memberArrayTS  = "{ path: string; title: string; file: string }[]"
)

func zodBase(kind conformancecatalog.ColumnKind) string {
	switch kind {
	case conformancecatalog.ColumnKindString:
		return "z.string()"
	case conformancecatalog.ColumnKindInt:
		return "z.number().int()"
	case conformancecatalog.ColumnKindNonNegInt:
		return "z.number().int().nonnegative()"
	case conformancecatalog.ColumnKindStringArray:
		return "z.array(z.string())"
	case conformancecatalog.ColumnKindMemberArray:
		return memberArrayZod
	default:
		panic(fmt.Sprintf("unknown column kind %q", kind))
	}
}

func writeTSFields(b *bytes.Buffer, cols []conformancecatalog.ClientColumn) {
	for _, c := range cols {
		ts := tsType(c.Kind)
		if c.Optional {
			b.WriteString(fmt.Sprintf("\t%s?: %s\n", c.Name, ts))
		} else {
			b.WriteString(fmt.Sprintf("\t%s: %s\n", c.Name, ts))
		}
	}
}

func tsType(kind conformancecatalog.ColumnKind) string {
	switch kind {
	case conformancecatalog.ColumnKindString:
		return "string"
	case conformancecatalog.ColumnKindInt, conformancecatalog.ColumnKindNonNegInt:
		return "number"
	case conformancecatalog.ColumnKindStringArray:
		return "string[]"
	case conformancecatalog.ColumnKindMemberArray:
		return memberArrayTS
	default:
		panic(fmt.Sprintf("unknown column kind %q", kind))
	}
}

func mustWrite(path, contents string) {
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", path, err)
		os.Exit(1)
	}
	fmt.Println("wrote", path)
}

func findRepoRoot() string {
	wd, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	dir := wd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			panic("go.mod not found from " + wd)
		}
		dir = parent
	}
}
