// SPDX-FileCopyrightText: 2026 Forkbomb BV
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by go generate ./pkg/conformancecatalog; DO NOT EDIT.
// Source of truth: schema.go columnSpec (ADR-0009).

package conformancecatalog

// Check is one catalog entry derived from a template file.
// Lean check grain: path, title, facets, and identity only. Suite display
// metadata (name, logo, URLs) lives on the suite projection (ADR-0002).
// Generated from checkColumns; HTTP list/get wraps it in checkHTTPRecord.
type Check struct {
	ID         string      `db:"id" json:"id"`
	Path       string      `db:"path" json:"path"`
	Title      string      `db:"title" json:"title"`
	FSStandard string      `db:"fs_standard" json:"fs_standard"`
	FSVersion  string      `db:"fs_version" json:"fs_version"`
	Suite      string      `db:"suite" json:"suite"`
	File       string      `db:"file" json:"file"`
	VisibleIn  stringArray `db:"visible_in" json:"visible_in"`
	Protocol   string      `db:"protocol" json:"protocol"`
	SUT        string      `db:"sut" json:"sut"`
	Role       string      `db:"role" json:"role"`
	Provider   string      `db:"provider" json:"provider"`
	Standard   string      `db:"standard" json:"standard"`
	Component  string      `db:"component" json:"component"`
	Version    string      `db:"version" json:"version"`
	Created    string      `db:"created" json:"created"`
	Updated    string      `db:"updated" json:"updated"`
}

// SuiteRecord is one hub-table row: a suite under normalized standard×component×version.
// FS* fields preserve durable path identity for hub links; Standard/Component/Version
// are the product projection.
// Generated from suiteColumns; HTTP list/get wraps it in suiteHTTPRecord.
type SuiteRecord struct {
	ID               string      `db:"id" json:"id"`
	Standard         string      `db:"standard" json:"standard"`
	Component        string      `db:"component" json:"component"`
	ComponentRank    int         `db:"component_rank" json:"component_rank"`
	Version          string      `db:"version" json:"version"`
	Suite            string      `db:"suite" json:"suite"`
	Provider         string      `db:"provider" json:"provider"`
	ProviderLabel    string      `db:"provider_label" json:"provider_label"`
	SuiteName        string      `db:"suite_name" json:"suite_name"`
	SuiteSubtitle    string      `db:"suite_subtitle" json:"suite_subtitle"`
	SuiteHomepage    string      `db:"suite_homepage" json:"suite_homepage"`
	SuiteRepository  string      `db:"suite_repository" json:"suite_repository"`
	SuiteHelp        string      `db:"suite_help" json:"suite_help"`
	SuiteDescription string      `db:"suite_description" json:"suite_description"`
	SuiteLogo        string      `db:"suite_logo" json:"suite_logo"`
	CheckCount       int         `db:"check_count" json:"check_count"`
	Members          memberArray `db:"members" json:"members"`
	VisibleIn        stringArray `db:"visible_in" json:"visible_in"`
	FSStandard       string      `db:"fs_standard" json:"fs_standard"`
	FSVersion        string      `db:"fs_version" json:"fs_version"`
	PathPrefix       string      `db:"path_prefix" json:"path_prefix"`
	Created          string      `db:"created" json:"created"`
	Updated          string      `db:"updated" json:"updated"`
}
