// SPDX-FileCopyrightText: 2025 Forkbomb BV
//
// SPDX-License-Identifier: AGPL-3.0-or-later
package workflows

import "github.com/forkbombeu/credimi/pkg/workflowengine/mobilerunnersemaphore"

const (
	MobileRunnerSemaphoreTaskQueue            = mobilerunnersemaphore.TaskQueue
	MobileRunnerSemaphoreWorkflowName         = mobilerunnersemaphore.WorkflowName
	MobileRunnerSemaphoreStateQuery           = mobilerunnersemaphore.StateQuery
	MobileRunnerSemaphoreEnqueueRunUpdate     = mobilerunnersemaphore.EnqueueRunUpdate
	MobileRunnerSemaphoreRunStatusQuery       = mobilerunnersemaphore.RunStatusQuery
	MobileRunnerSemaphoreListQueuedRunsQuery  = mobilerunnersemaphore.ListQueuedRunsQuery
	MobileRunnerSemaphoreRunDoneUpdate        = mobilerunnersemaphore.RunDoneUpdate
	MobileRunnerSemaphoreCancelRunUpdate      = mobilerunnersemaphore.CancelRunUpdate
	MobileRunnerSemaphorePauseRunnerUpdate    = mobilerunnersemaphore.PauseRunnerUpdate
	MobileRunnerSemaphoreResumeRunnerUpdate   = mobilerunnersemaphore.ResumeRunnerUpdate
	MobileRunnerSemaphoreShutdownRunnerUpdate = mobilerunnersemaphore.ShutdownRunnerUpdate
	MobileRunnerSemaphoreRunGrantedSignalName = mobilerunnersemaphore.RunGrantedSignal
	MobileRunnerSemaphoreRunStartedSignalName = mobilerunnersemaphore.RunStartedSignal
	MobileRunnerSemaphoreRunDoneSignalName    = mobilerunnersemaphore.RunDoneSignal

	MobileRunnerSemaphoreErrInvalidRequest     = mobilerunnersemaphore.ErrInvalidRequest
	MobileRunnerSemaphoreErrQueueLimitExceeded = mobilerunnersemaphore.ErrQueueLimitExceeded
)

type MobileRunnerSemaphoreWorkflowInput = mobilerunnersemaphore.MobileRunnerSemaphoreWorkflowInput

type MobileRunnerSemaphoreWorkflowState = mobilerunnersemaphore.MobileRunnerSemaphoreWorkflowState

type MobileRunnerSemaphoreStateView = mobilerunnersemaphore.MobileRunnerSemaphoreStateView

type MobileRunnerSemaphoreRunStatus = mobilerunnersemaphore.MobileRunnerSemaphoreRunStatus

type MobileRunnerSemaphoreEnqueueRunRequest = mobilerunnersemaphore.MobileRunnerSemaphoreEnqueueRunRequest

type MobileRunnerSemaphoreCleanupMetadata = mobilerunnersemaphore.MobileRunnerSemaphoreCleanupMetadata

type MobileRunnerSemaphoreTempCredentialCleanupMetadata = mobilerunnersemaphore.MobileRunnerSemaphoreTempCredentialCleanupMetadata

type MobileRunnerSemaphoreNotification = mobilerunnersemaphore.MobileRunnerSemaphoreNotification

type MobileRunnerSemaphoreGitHubPRNotification = mobilerunnersemaphore.MobileRunnerSemaphoreGitHubPRNotification

type MobileRunnerSemaphoreEnqueueRunResponse = mobilerunnersemaphore.MobileRunnerSemaphoreEnqueueRunResponse

type MobileRunnerSemaphoreRunStatusView = mobilerunnersemaphore.MobileRunnerSemaphoreRunStatusView

type MobileRunnerSemaphoreQueuedRunView = mobilerunnersemaphore.MobileRunnerSemaphoreQueuedRunView

type MobileRunnerSemaphoreRunDoneRequest = mobilerunnersemaphore.MobileRunnerSemaphoreRunDoneRequest

type MobileRunnerSemaphoreRunCancelRequest = mobilerunnersemaphore.MobileRunnerSemaphoreRunCancelRequest

type MobileRunnerSemaphoreShutdownRunnerRequest = mobilerunnersemaphore.MobileRunnerSemaphoreShutdownRunnerRequest

type MobileRunnerSemaphorePauseRunnerRequest = mobilerunnersemaphore.MobileRunnerSemaphorePauseRunnerRequest

type MobileRunnerSemaphorePauseRunnerResponse = mobilerunnersemaphore.MobileRunnerSemaphorePauseRunnerResponse

type MobileRunnerSemaphoreResumeRunnerRequest = mobilerunnersemaphore.MobileRunnerSemaphoreResumeRunnerRequest

type MobileRunnerSemaphoreResumeRunnerResponse = mobilerunnersemaphore.MobileRunnerSemaphoreResumeRunnerResponse

type MobileRunnerSemaphoreShutdownRunnerResponse = mobilerunnersemaphore.MobileRunnerSemaphoreShutdownRunnerResponse

type MobileRunnerSemaphoreRunGrantedSignal = mobilerunnersemaphore.MobileRunnerSemaphoreRunGrantedSignal

type MobileRunnerSemaphoreRunStartedSignal = mobilerunnersemaphore.MobileRunnerSemaphoreRunStartedSignal

type MobileRunnerSemaphoreRunDoneSignal = mobilerunnersemaphore.MobileRunnerSemaphoreRunDoneSignal

type MobileRunnerSemaphoreRunTicketState = mobilerunnersemaphore.MobileRunnerSemaphoreRunTicketState

func MobileRunnerSemaphoreWorkflowID(runnerID string) string {
	return mobilerunnersemaphore.WorkflowID(runnerID)
}
