# SPDX-FileCopyrightText: 2025 Forkbomb BV
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: "👺 Lint PR title"
on:
  pull_request:

jobs:
  uses: forkbombeu/.github/.github/workflows/pr-conventional-title.yml@main
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
