# SPDX-FileCopyrightText: 2025 Forkbomb BV
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: 🚦 Update version
permissions:
  contents: write
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'VERSION'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  version:
    name: 🚦 Update version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: jdx/mise-action@v2
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
            github-token: '${{ secrets.GITHUB_TOKEN }}'
            dry: true
      - if: steps.semrel.outputs.version != ''
        run: |
            echo ${{ steps.semrel.outputs.version }} > VERSION
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          file_pattern: 'VERSION'
          commit_message: "chore(release): 🚀 update VERSION to ${{ steps.semrel.outputs.version }}"
